/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#faf9f8",
        "surface-container-high": "#e9e8e7",
        "on-background": "#1a1c1c",
        "on-primary-fixed-variant": "#464745",
        "primary-container": "#1b1c1b",
        "on-secondary-container": "#56645c",
        "error": "#ba1a1a",
        "secondary": "#536259",
        "secondary-fixed": "#d7e6dc",
        "on-error-container": "#93000a",
        "surface-container-low": "#f4f3f2",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#1b1c1b",
        "surface-variant": "#e3e2e1",
        "outline": "#757874",
        "on-secondary": "#ffffff",
        "outline-variant": "#c5c7c3",
        "primary-fixed": "#e4e2e0",
        "on-surface-variant": "#444844",
        "secondary-container": "#d1e1d6",
        "primary-fixed-dim": "#c7c6c4",
        "inverse-surface": "#2f3130",
        "on-tertiary-container": "#7a877f",
        "inverse-on-surface": "#f1f0f0",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#bdcac0",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d9e6dc",
        "surface-tint": "#5e5e5d",
        "surface-container": "#eeeeed",
        "primary": "#000000",
        "on-secondary-fixed-variant": "#3c4a42",
        "secondary-fixed-dim": "#bbcac0",
        "surface-bright": "#faf9f8",
        "tertiary": "#000000",
        "surface-dim": "#dadad9",
        "on-secondary-fixed": "#111e18",
        "on-primary-container": "#848482",
        "surface": "#faf9f8",
        "surface-container-highest": "#e3e2e1",
        "tertiary-container": "#131e18",
        "on-tertiary-fixed-variant": "#3e4942",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#131e18",
        "inverse-primary": "#c7c6c4",
        "on-surface": "#1a1c1c",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-sm": "0.75rem",
        "gutter": "2rem",
        "space-md": "1.5rem",
        "space-lg": "2.5rem",
        "space-xs": "0.375rem",
        "gutter-mobile": "1rem",
        "margin": "4rem",
        "space-xl": "4.5rem",
        "margin-mobile": "1.5rem"
      },
      fontFamily: {
        "headline-md": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "display": ["Newsreader", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-reading": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "verse-number": ["Inter", "sans-serif"],
        "display-mobile": ["Newsreader", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-ui": ["Inter", "sans-serif"],
        "body-reading-mobile": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"]
      },
      fontSize: {
        "headline-md": ["1.75rem", { "lineHeight": "2.25rem", "fontWeight": "400" }],
        "headline-lg": ["2.5rem", { "lineHeight": "3rem", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "display": ["3.5rem", { "lineHeight": "4.25rem", "letterSpacing": "-0.02em", "fontWeight": "300" }],
        "label-sm": ["0.6875rem", { "lineHeight": "0.875rem", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "body-reading": ["1.375rem", { "lineHeight": "2.375rem", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "headline-lg-mobile": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "verse-number": ["0.6875rem", { "lineHeight": "1rem", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "display-mobile": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.015em", "fontWeight": "300" }],
        "label-md": ["0.8125rem", { "lineHeight": "1.125rem", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "body-ui": ["0.9375rem", { "lineHeight": "1.5rem", "fontWeight": "400" }],
        "body-reading-mobile": ["1.1875rem", { "lineHeight": "2rem", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "headline-sm": ["1.25rem", { "lineHeight": "1.75rem", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
